<<<<<<< HEAD
export const GET_LIST_STICKER2 = "GET_LIST_STICKER2"
export const RESP_GET_STICKER_LIST2 = "RESP_GET_STICKER_LIST2"

export const GET_STICKER = "GET_STICKER"
export const RESP_GET_STICKER = "RESP_GET_STICKER"

export const SAVE_STICKER = "SAVE_STICKER"
export const EDIT_STICKER = "EDIT_STICKER"
export const DELETE_STICKER = "DELETE_STICKER"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
=======
export const GET_LIST_STICKER2 = "GET_LIST_STICKER2"
export const RESP_GET_STICKER_LIST2 = "RESP_GET_STICKER_LIST2"

export const GET_STICKER = "GET_STICKER"
export const RESP_GET_STICKER = "RESP_GET_STICKER"

export const SAVE_STICKER = "SAVE_STICKER"
export const EDIT_STICKER = "EDIT_STICKER"
export const DELETE_STICKER = "DELETE_STICKER"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
>>>>>>> f23d2f551239199f028f5e8870adde7381ad99ca
export const RESET_MESSAGE = "RESET_MESSAGE"