export const GET_LAPORAN_DIV_RATE = "GET_LAPORAN_DIV_RATE"
export const RESP_GET_LAPORAN_DIV_RATE = "RESP_GET_LAPORAN_DIV_RATE"

export const GET_LOCATION_DIV_RATE = "GET_LOCATION_DIV_RATE"
export const RESP_GET_LOCATION_DIV_RATE = "RESP_GET_LOCATION_DIV_RATE"

export const GET_DEPT_DIV_RATE = "GET_DEPT_DIV_RATE"
export const RESP_GET_DEPT_DIV_RATE = "RESP_GET_DEPT_DIV_RATE"

export const DOWNLOAD_DIV_RATE = "DOWNLOAD_DIV_RATE"
export const RESP_DOWNLOAD = "RESP_DOWNLOAD"

// export const SAVE_LOCATION = "SAVE_LOCATION"
// export const EDIT_LOCATION = "EDIT_LOCATION"
// export const DELETE_LOCATION = "DELETE_LOCATION"

// export const MSG_ADD = "MSG_ADD"
// export const MSG_EDIT = "MSG_EDIT"
// export const MSG_DELETE = "MSG_DELETE"
export const RESET_MESSAGE = "RESET_MESSAGE"