<<<<<<< HEAD
export const GET_LIST_SETTING = "GET_LIST_SETTING"
export const RESP_GET_SETTING_LIST = "RESP_GET_SETTING_LIST"

export const GET_SETTING2 = "GET_SETTING2"
export const RESP_GET_SETTING2 = "RESP_GET_SETTING2"

export const SAVE_SETTING = "SAVE_SETTING"
export const EDIT_SETTING = "EDIT_SETTING"
export const DELETE_SETTING = "DELETE_SETTING"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
=======
export const GET_LIST_SETTING = "GET_LIST_SETTING"
export const RESP_GET_SETTING_LIST = "RESP_GET_SETTING_LIST"

export const GET_SETTING2 = "GET_SETTING2"
export const RESP_GET_SETTING2 = "RESP_GET_SETTING2"

export const SAVE_SETTING = "SAVE_SETTING"
export const EDIT_SETTING = "EDIT_SETTING"
export const DELETE_SETTING = "DELETE_SETTING"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
>>>>>>> f23d2f551239199f028f5e8870adde7381ad99ca
export const RESET_MESSAGE = "RESET_MESSAGE"