export const GET_LIST = "GET_LIST"
export const RESP_GET_LIST = "RESP_GET_LIST"

export const GET_YEAR_LIST = "GET_YEAR_LIST"
export const RESP_GET_YEAR_LIST = "RESP_GET_YEAR_LIST"

export const GET_KEYWORD_LIST = "GET_KEYWORD_LIST"
export const RESP_GET_KEYWORD_LIST = "RESP_GET_KEYWORD_LIST"

export const GET_CANDIDATE_LIST = "GET_CANDIDATE_LIST"
export const RESP_GET_CANDIDATE_LIST = "RESP_GET_CANDIDATE_LIST"

export const GET_CANDIDATE = "GET_CANDIDATE"
export const RESP_GET_CANDIDATE = "RESP_GET_CANDIDATE"

export const ADD_EMPLOYEE_OF = "ADD_EMPLOYEE_OF"
export const EDIT_EMPLOYEE_OF = "EDIT_EMPLOYEE_OF"
export const DELETE_EMPLOYEE_OF = "DELETE_EMPLOYEE_OF"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
export const RESET_MESSAGE = "RESET_MESSAGE"