<<<<<<< HEAD
export const GET_LIST_REPORT2 = "GET_LIST_REPORT2"
export const RESP_GET_REPORT_LIST2 = "RESP_GET_REPORT_LIST2"

export const GET_STATUS_REPORT = "GET_STATUS_REPORT"
export const RESP_GET_STATUS_REPORT = "RESP_GET_STATUS_REPORT"

export const EDIT_REPORT = "EDIT_REPORT"

export const MSG_EDIT = "MSG_EDIT"

=======
export const GET_LIST_REPORT2 = "GET_LIST_REPORT2"
export const RESP_GET_REPORT_LIST2 = "RESP_GET_REPORT_LIST2"

export const GET_STATUS_REPORT = "GET_STATUS_REPORT"
export const RESP_GET_STATUS_REPORT = "RESP_GET_STATUS_REPORT"

export const EDIT_REPORT = "EDIT_REPORT"

export const MSG_EDIT = "MSG_EDIT"

>>>>>>> f23d2f551239199f028f5e8870adde7381ad99ca
export const RESET_MESSAGE = "RESET_MESSAGE"