<<<<<<< HEAD
export const GET_LIST_POSITION = "GET_LIST_POSITION"
export const RESP_GET_POSITION_LIST = "RESP_GET_POSITION_LIST"
export const GET_LIST_LOCATION3 = "GET_LIST_LOCATION3"
export const RESP_GET_LOCATION_LIST3 = "RESP_GET_LOCATION_LIST3"
export const GET_LIST_LEVEL2 = "GET_LIST_LEVEL2"
export const RESP_GET_LEVEL_LIST2 = "RESP_GET_LEVEL_LIST2"

export const GET_POSITION2 = "GET_POSITION2"
export const RESP_GET_POSITION2 = "RESP_GET_POSITION2"

export const SAVE_POSITION = "SAVE_POSITION"
export const EDIT_POSITION = "EDIT_POSITION"
export const DELETE_POSITION = "DELETE_POSITION"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
=======
export const GET_LIST_POSITION = "GET_LIST_POSITION"
export const RESP_GET_POSITION_LIST = "RESP_GET_POSITION_LIST"
export const GET_LIST_LOCATION3 = "GET_LIST_LOCATION3"
export const RESP_GET_LOCATION_LIST3 = "RESP_GET_LOCATION_LIST3"
export const GET_LIST_LEVEL2 = "GET_LIST_LEVEL2"
export const RESP_GET_LEVEL_LIST2 = "RESP_GET_LEVEL_LIST2"

export const GET_POSITION2 = "GET_POSITION2"
export const RESP_GET_POSITION2 = "RESP_GET_POSITION2"

export const SAVE_POSITION = "SAVE_POSITION"
export const EDIT_POSITION = "EDIT_POSITION"
export const DELETE_POSITION = "DELETE_POSITION"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
>>>>>>> f23d2f551239199f028f5e8870adde7381ad99ca
export const RESET_MESSAGE = "RESET_MESSAGE"