<<<<<<< HEAD
export const GET_LAPORAN_ALL_DATA = "GET_LAPORAN_ALL_DATA"
export const RESP_GET_LAPORAN_ALL_DATA = "RESP_GET_LAPORAN_ALL_DATA"

export const GET_LOCATION_ALL_DATA = "GET_LOCATION_ALL_DATA"
export const RESP_GET_LOCATION_ALL_DATA = "RESP_GET_LOCATION_ALL_DATA"

export const GET_DEPT_ALL_DATA = "GET_DEPT_ALL_DATA"
export const RESP_GET_DEPT_ALL_DATA = "RESP_GET_DEPT_ALL_DATA"

export const DOWNLOAD_ALL_DATA = "DOWNLOAD_ALL_DATA"
export const RESP_DOWNLOAD = "RESP_DOWNLOAD"

// export const SAVE_LOCATION = "SAVE_LOCATION"
// export const EDIT_LOCATION = "EDIT_LOCATION"
// export const DELETE_LOCATION = "DELETE_LOCATION"

// export const MSG_ADD = "MSG_ADD"
// export const MSG_EDIT = "MSG_EDIT"
// export const MSG_DELETE = "MSG_DELETE"
=======
export const GET_LAPORAN_ALL_DATA = "GET_LAPORAN_ALL_DATA"
export const RESP_GET_LAPORAN_ALL_DATA = "RESP_GET_LAPORAN_ALL_DATA"

export const GET_LOCATION_ALL_DATA = "GET_LOCATION_ALL_DATA"
export const RESP_GET_LOCATION_ALL_DATA = "RESP_GET_LOCATION_ALL_DATA"

export const GET_DEPT_ALL_DATA = "GET_DEPT_ALL_DATA"
export const RESP_GET_DEPT_ALL_DATA = "RESP_GET_DEPT_ALL_DATA"

export const DOWNLOAD_ALL_DATA = "DOWNLOAD_ALL_DATA"
export const RESP_DOWNLOAD = "RESP_DOWNLOAD"

// export const SAVE_LOCATION = "SAVE_LOCATION"
// export const EDIT_LOCATION = "EDIT_LOCATION"
// export const DELETE_LOCATION = "DELETE_LOCATION"

// export const MSG_ADD = "MSG_ADD"
// export const MSG_EDIT = "MSG_EDIT"
// export const MSG_DELETE = "MSG_DELETE"
>>>>>>> f23d2f551239199f028f5e8870adde7381ad99ca
export const RESET_MESSAGE = "RESET_MESSAGE"