<<<<<<< HEAD
export const GET_LIST_LEVEL = "GET_LIST_LEVEL"
export const RESP_GET_LEVEL_LIST = "RESP_GET_LEVEL_LIST"
export const GET_LIST_LOCATION3 = "GET_LIST_LOCATION3"
export const RESP_GET_LOCATION_LIST3 = "RESP_GET_LOCATION_LIST3"

export const GET_LEVEL2 = "GET_LEVEL2"
export const RESP_GET_LEVEL2 = "RESP_GET_LEVEL2"

export const SAVE_LEVEL = "SAVE_LEVEL"
export const EDIT_LEVEL = "EDIT_LEVEL"
export const DELETE_LEVEL = "DELETE_LEVEL"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
=======
export const GET_LIST_LEVEL = "GET_LIST_LEVEL"
export const RESP_GET_LEVEL_LIST = "RESP_GET_LEVEL_LIST"
export const GET_LIST_LOCATION3 = "GET_LIST_LOCATION3"
export const RESP_GET_LOCATION_LIST3 = "RESP_GET_LOCATION_LIST3"

export const GET_LEVEL2 = "GET_LEVEL2"
export const RESP_GET_LEVEL2 = "RESP_GET_LEVEL2"

export const SAVE_LEVEL = "SAVE_LEVEL"
export const EDIT_LEVEL = "EDIT_LEVEL"
export const DELETE_LEVEL = "DELETE_LEVEL"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
>>>>>>> f23d2f551239199f028f5e8870adde7381ad99ca
export const RESET_MESSAGE = "RESET_MESSAGE"