export const GET_LIST_MEMBER = "GET_LIST_MEMBER"
export const RESP_GET_MEMBER_LIST = "RESP_GET_MEMBER_LIST"
export const GET_LIST_LOCATION5 = "GET_LIST_LOCATION5"
export const RESP_GET_LOCATION_LIST5 = "RESP_GET_LOCATION_LIST5"

export const GET_MEMBER2 = "GET_MEMBER2"
export const RESP_GET_MEMBER2 = "RESP_GET_MEMBER2"

export const SAVE_MEMBER = "SAVE_MEMBER"
export const EDIT_MEMBER = "EDIT_MEMBER"
export const DELETE_MEMBER = "DELETE_MEMBER"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
export const RESET_MESSAGE = "RESET_MESSAGE"