<<<<<<< HEAD
export const LOV_CANDIDATE = "LOV_CANDIDATE"
export const LOV_LEVEL = "LOV_LEVEL"
export const LOV_DEPT_LIST_ORG = "LOV_DEPT_LIST_ORG"
export const LOV_POSITION_AND_LEVEL = "LOV_POSITION_AND_LEVEL"
export const LOV_MENU_ROLE_LIST = "LOV_MENU_ROLE_LIST"
export const LOV_USER_ROLE_LIST = "LOV_USER_ROLE_LIST"
export const LOV_MEMBER_LIST = "LOV_MEMBER_LIST"
export const LOV_MENU_PARENT_LIST = "LOV_MENU_PARENT_LIST"

=======
export const LOV_CANDIDATE = "LOV_CANDIDATE"
export const LOV_LEVEL = "LOV_LEVEL"
export const LOV_DEPT_LIST_ORG = "LOV_DEPT_LIST_ORG"
export const LOV_POSITION_AND_LEVEL = "LOV_POSITION_AND_LEVEL"
export const LOV_MENU_ROLE_LIST = "LOV_MENU_ROLE_LIST"
export const LOV_USER_ROLE_LIST = "LOV_USER_ROLE_LIST"
export const LOV_MEMBER_LIST = "LOV_MEMBER_LIST"
export const LOV_MENU_PARENT_LIST = "LOV_MENU_PARENT_LIST"

>>>>>>> f23d2f551239199f028f5e8870adde7381ad99ca
export const MSG_LOV = "MSG_LOV"