export const GET_MANUAL_VIDEO = "GET_MANUAL_VIDEO"
export const RESP_GET_MANUAL_VIDEO = "RESP_GET_MANUAL_VIDEO"

export const GET_MANUAL_PDF = "GET_MANUAL_PDF"
export const RESP_GET_MANUAL_PDF = "RESP_GET_MANUAL_PDF"