<<<<<<< HEAD
export const GET_MANUAL_VIDEO = "GET_MANUAL_VIDEO"
export const RESP_GET_MANUAL_VIDEO = "RESP_GET_MANUAL_VIDEO"

export const GET_MANUAL_PDF = "GET_MANUAL_PDF"
=======
export const GET_MANUAL_VIDEO = "GET_MANUAL_VIDEO"
export const RESP_GET_MANUAL_VIDEO = "RESP_GET_MANUAL_VIDEO"

export const GET_MANUAL_PDF = "GET_MANUAL_PDF"
>>>>>>> f23d2f551239199f028f5e8870adde7381ad99ca
export const RESP_GET_MANUAL_PDF = "RESP_GET_MANUAL_PDF"