export const GET_BEST_LIST = "GET_BEST_LIST"
export const RESP_GET_BEST_LIST = "RESP_GET_BEST_LIST"

export const GET_BEST_OF_MONTH_LIST = "GET_BEST_OF_MONTH_LIST"
export const RESP_GET_BEST_OF_MONTH_LIST = "RESP_GET_BEST_OF_MONTH_LIST"

export const GET_BEST_OF_YEAR_LIST = "GET_BEST_OF_YEAR_LIST"
export const RESP_GET_BEST_OF_YEAR_LIST = "RESP_GET_BEST_OF_YEAR_LIST"

export const GET_DETAIL_INFLUENCER = "GET_DETAIL_INFLUENCER"
export const RESP_GET_DETAIL_INFLUENCER = "RESP_GET_DETAIL_INFLUENCER"

export const GET_REPORT_LIST = "GET_REPORT_LIST"
export const RESP_GET_REPORT_LIST = "RESP_GET_REPORT_LIST"