export const MSGADD = "MSGADD"
export const RESET_MESSAGE = "RESET_MESSAGE"


export const GET_PROJECT_LIST = "GET_PROJECT_LIST"
export const RESP_GET_PROJECT_LIST = "RESP_GET_PROJECT_LIST"

export const ADD_PROJECT_LIST = "ADD_PROJECT_LIST"

export const ADD_SCHEDULE = "ADD_SCHEDULE"