export const GET_LIST_ROLE = "GET_LIST_ROLE"
export const RESP_GET_ROLE_LIST = "RESP_GET_ROLE_LIST"

export const GET_ACCESS_LIST_ROLE = "GET_ACCESS_LIST_ROLE"
export const RESP_GET_ACCESS_LIST_ROLE = "RESP_GET_ACCESS_LIST_ROLE"

export const GET_USER_LIST_ROLE = "GET_USER_LIST_ROLE"
export const RESP_GET_USER_LIST_ROLE = "RESP_GET_USER_LIST_ROLE"

export const GET_ROLE = "GET_ROLE"
export const RESP_GET_ROLE = "RESP_GET_ROLE"

export const SAVE_ROLE = "SAVE_ROLE"
export const EDIT_ROLE = "EDIT_ROLE"
export const DELETE_ROLE = "DELETE_ROLE"

export const SAVE_APPLICATION_ROLE_ACCESS = "SAVE_APPLICATION_ROLE_ACCESS"
export const EDIT_APPLICATION_ROLE_ACCESS = "EDIT_APPLICATION_ROLE_ACCESS"
export const DELETE_APPLICATION_ROLE_ACCESS = "DELETE_APPLICATION_ROLE_ACCESS"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"
export const RESET_MESSAGE = "RESET_MESSAGE"