export const GET_DEPT_LIST_ORG = "GET_DEPT_LIST_ORG"
export const RESP_GET_DEPT_LIST_ORG = "RESP_GET_DEPT_LIST_ORG"

export const GET_ORGANIZATION_LIST = "GET_ORGANIZATION_LIST"
export const RESP_GET_ORGANIZATION_LIST = "RESP_GET_ORGANIZATION_LIST"

// export const GET_SEARCH = "GET_SEARCH"
// export const RESP_GET_SEARCH = "RESP_GET_SEARCH"

// export const GET_RECOMMEND_LIST = "GET_RECOMMEND_LIST"
// export const RESP_GET_RECOMMEND_LIST = "RESP_GET_RECOMMEND_LIST"

// export const GET_RECOMMEND = "GET_RECOMMEND"
// export const RESP_GET_RECOMMEND = "RESP_GET_RECOMMEND"

// export const GET_STICKER_LIST = "GET_STICKER_LIST"
// export const RESP_GET_STICKER_LIST = "RESP_GET_STICKER_LIST"

// export const ADD_RECOMMEND = "ADD_RECOMMEND"
// export const EDIT_RECOMMEND = "EDIT_RECOMMEND"
// export const DELETE_RECOMMEND = "DELETE_RECOMMEND"

// export const SUBMIT_RECOMMEND = "SUBMIT_RECOMMEND"

// export const RESET_MESSAGE = "RESET_MESSAGE"

// export const MSG_ADD = "MSG_ADD"
// export const MSG_EDIT = "MSG_EDIT"
// export const MSG_DELETE = "MSG_DELETE"