export const GET_DEPT_LIST_ORG = "GET_DEPT_LIST_ORG"
export const RESP_GET_DEPT_LIST_ORG = "RESP_GET_DEPT_LIST_ORG"

export const GET_ORGANIZATION_LIST = "GET_ORGANIZATION_LIST"
export const RESP_GET_ORGANIZATION_LIST = "RESP_GET_ORGANIZATION_LIST"

export const GET_MEMBER_LIST_ORG = "GET_MEMBER_LIST_ORG"
export const RESP_GET_MEMBER_LIST_ORG = "RESP_GET_MEMBER_LIST_ORG"

export const GET_MEMBER_LIST_FOR_ADD = "GET_MEMBER_LIST_FOR_ADD"
export const RESP_GET_MEMBER_LIST_FOR_ADD = "RESP_GET_MEMBER_LIST_FOR_ADD"

export const SAVE_MAPPING_DEPT = "SAVE_MAPPING_DEPT"
export const SAVE_MAPPING_MEMBER = "SAVE_MAPPING_MEMBER"
export const EDIT_MAPPING_DEPT = "EDIT_MAPPING_DEPT"
export const EDIT_MAPPING_MEMBER = "EDIT_MAPPING_MEMBER"
export const DELETE_MAPPING_DEPT = "DELETE_MAPPING_DEPT"
export const DELETE_MAPPING_MEMBER = "DELETE_MAPPING_MEMBER"

export const RESET_MESSAGE = "RESET_MESSAGE"

export const MSG_ADD = "MSG_ADD"
export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"