export const GET_DEPT = "GET_DEPT"
export const RESP_GET_DEPT = "RESP_GET_DEPT"

export const GET_DETAIL_DEPT = "GET_DETAIL_DEPT"
export const RESP_GET_DETAIL_DEPT = "RESP_GET_DETAIL_DEPT"

export const GET_MEMBER_LIST = "GET_MEMBER_LIST"
export const RESP_GET_MEMBER_LIST = "RESP_GET_MEMBER_LIST"

export const GET_MEMBER_DETAIL = "GET_MEMBER_DETAIL"
export const RESP_GET_MEMBER_DETAIL = "RESP_GET_MEMBER_DETAIL"

export const GET_SEARCH = "GET_SEARCH"
export const RESP_GET_SEARCH = "RESP_GET_SEARCH"

export const GET_SERVICE_DEPT = "GET_SERVICE_DEPT"
export const RESP_GET_SERVICE_DEPT = "RESP_GET_SERVICE_DEPT"

export const GET_SERVICE_MEMBER = "GET_SERVICE_MEMBER"
export const RESP_GET_SERVICE_MEMBER = "RESP_GET_SERVICE_MEMBER"

export const EDIT_SERVICE_MEMBER = "EDIT_SERVICE_MEMBER"
export const EDIT_SERVICE_DEPT = "EDIT_SERVICE_DEPT"
export const MSG_EDIT = "MSG_EDIT"

export const RESET_MESSAGE = "RESET_MESSAGE"
export const RESET_MESSAGE_MEMBER_DETAIL = "RESET_MESSAGE_MEMBER_DETAIL"